# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2017-08-29 07:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmdb', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='server',
            name='ip',
            field=models.CharField(max_length=255, null=True, unique=True, verbose_name='\u670d\u52a1\u5668IP\u5730\u5740'),
        ),
    ]
