# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2017-08-30 20:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, null=True, unique=True, verbose_name='\u8d26\u6237\u540d\u79f0')),
                ('desc', models.CharField(max_length=255, null=True, verbose_name='\u63cf\u8ff0')),
                ('creater', models.CharField(max_length=255, null=True, verbose_name='\u521b\u5efa\u4eba')),
                ('createTime', models.DateTimeField(auto_now_add=True, null=True, verbose_name='\u521b\u5efa\u65f6\u95f4')),
                ('ModifyUser', models.CharField(max_length=255, null=True, verbose_name='\u4fee\u6539\u4eba')),
                ('ModifyTime', models.DateTimeField(auto_now=True, null=True, verbose_name='\u4fee\u6539\u65f6\u95f4')),
            ],
            options={
                'db_table': 'account',
                'permissions': (('view_account', '\u67e5\u770b\u8d26\u6237'), ('edit_account', '\u7f16\u8f91\u8d26\u6237')),
            },
        ),
    ]
