# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2017-09-20 22:49
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Script',
            new_name='Nm_Script',
        ),
        migrations.AlterModelTable(
            name='nm_script',
            table='nm_script',
        ),
    ]
