# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-01-02 08:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Applications',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='\u540d\u79f0')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='\u6807\u8bc6\u7b26')),
                ('note', models.TextField(blank=True, null=True, verbose_name=b'\xe5\xa4\x87\xe6\xb3\xa8')),
            ],
        ),
        migrations.CreateModel(
            name='EnvIronMent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='\u540d\u79f0')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='\u6807\u8bc6\u7b26')),
                ('note', models.TextField(blank=True, null=True, verbose_name=b'\xe5\xa4\x87\xe6\xb3\xa8')),
            ],
        ),
        migrations.CreateModel(
            name='Projects',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='\u9879\u76ee\u540d\u79f0')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='\u6807\u8bc6\u7b26')),
                ('createTime', models.DateTimeField(default=django.utils.timezone.now, verbose_name='\u6570\u636e\u521b\u5efa\u65f6\u95f4')),
                ('updateTime', models.DateTimeField(default=django.utils.timezone.now, verbose_name='\u6570\u636e\u66f4\u65b0\u65f6\u95f4')),
                ('Applications', models.ManyToManyField(to='projectdata.Applications', verbose_name='\u5e94\u7528\u5173\u8054')),
                ('EnvIronMent', models.ManyToManyField(to='projectdata.EnvIronMent', verbose_name='\u73af\u5883\u5173\u8054')),
            ],
            options={
                'verbose_name': '\u53d1\u5e03-\u83dc\u5355',
                'verbose_name_plural': '\u53d1\u5e03-\u83dc\u5355',
            },
        ),
    ]
