# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-01-02 08:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectdata', '0002_auto_20180102_1643'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projects',
            name='Applications',
            field=models.ManyToManyField(to='projectdata.Applications', verbose_name='\u5e94\u7528\u5173\u8054'),
        ),
    ]
