# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-01-03 02:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectdata', '0003_auto_20180102_1644'),
    ]

    operations = [
        migrations.AddField(
            model_name='applications',
            name='AppData',
            field=models.TextField(blank=True, help_text=b'\xe5\x9f\xba\xe7\xa1\x80\xe6\x95\xb0\xe6\x8d\xae\xe9\x9b\x86\xe5\x90\x88,\xe8\xaf\xb7\xe5\xad\x98\xe8\xb4\xaedict\xe5\xad\x97\xe5\x85\xb8', null=True, verbose_name=b'\xe5\x9f\xba\xe7\xa1\x80\xe6\x95\xb0\xe6\x8d\xae\xe9\x9b\x86\xe5\x90\x88'),
        ),
        migrations.AddField(
            model_name='applications',
            name='HostsData',
            field=models.TextField(blank=True, help_text=b'\xe4\xb8\xbb\xe6\x9c\xba\xe5\x88\x97\xe8\xa1\xa8,\xe8\xaf\xb7\xe5\xad\x98\xe8\xb4\xaelist\xe5\x88\x97\xe8\xa1\xa8', null=True, verbose_name=b'\xe4\xb8\xbb\xe6\x9c\xba\xe5\x88\x97\xe8\xa1\xa8'),
        ),
        migrations.AlterField(
            model_name='applications',
            name='note',
            field=models.TextField(blank=True, help_text=b'\xe6\xa0\x87\xe5\x87\x86\xe5\xa4\x87\xe6\xb3\xa8\xe5\x95\x8a', null=True, verbose_name=b'\xe5\xa4\x87\xe6\xb3\xa8'),
        ),
    ]
