# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-01-08 08:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectdata', '0004_auto_20180103_1016'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projects',
            name='Applications',
            field=models.ManyToManyField(blank=True, null=True, to='projectdata.Applications', verbose_name='\u5e94\u7528\u5173\u8054'),
        ),
        migrations.AlterField(
            model_name='projects',
            name='EnvIronMent',
            field=models.ManyToManyField(blank=True, null=True, to='projectdata.EnvIronMent', verbose_name='\u73af\u5883\u5173\u8054'),
        ),
    ]
