# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2017-09-11 21:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Nm_Instance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('taskId', models.IntegerField(null=True, verbose_name='\u6267\u884c\u4f5c\u4e1aid')),
                ('appId', models.IntegerField(null=True, verbose_name='\u4e1a\u52a1id')),
                ('name', models.CharField(max_length=255, null=True, verbose_name='\u4f5c\u4e1a\u540d\u79f0')),
                ('operator', models.CharField(max_length=255, null=True, verbose_name='\u6267\u884c\u4eba')),
                ('startWay', models.IntegerField(null=True, verbose_name='\u542f\u52a8\u65b9\u5f0f')),
                ('currentStepId', models.IntegerField(null=True, verbose_name='\u5f53\u524d\u6267\u884c\u6b65\u9aa4id')),
                ('status', models.IntegerField(default=1, null=True, verbose_name='\u72b6\u6001')),
                ('startTime', models.DateTimeField(null=True, verbose_name='\u5f00\u59cb\u65f6\u95f4')),
                ('endTime', models.DateTimeField(null=True, verbose_name='\u7ed3\u675f\u65f6\u95f4')),
                ('totalTime', models.FloatField(default=False, max_length=11, null=True, verbose_name='\u603b\u8017\u65f6')),
                ('createTime', models.DateTimeField(auto_now_add=True, null=True, verbose_name='\u521b\u5efa\u65f6\u95f4')),
                ('mobileTaskId', models.IntegerField(null=True, verbose_name='\u79fb\u52a8\u4f5c\u4e1aid')),
                ('tagId', models.IntegerField(null=True, verbose_name='\u6807\u7b7eId')),
            ],
            options={
                'db_table': 'nm_instance',
            },
        ),
    ]
