# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2017-09-11 21:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0002_nm_stepinstance'),
    ]

    operations = [
        migrations.CreateModel(
            name='Nm_ipList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.CharField(max_length=255, null=True, verbose_name='ip\u5730\u5740')),
                ('result', models.TextField(null=True, verbose_name='\u6267\u884c\u7ed3\u679c')),
                ('stepInstance_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='job.Nm_StepInstance', verbose_name='\u6267\u884c\u4f5c\u4e1a\u5b9e\u4f8b\u6b65\u9aa4id')),
            ],
            options={
                'db_table': 'nm_ipList',
            },
        ),
    ]
