# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2017-09-19 21:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0003_nm_iplist'),
    ]

    operations = [
        migrations.AddField(
            model_name='nm_stepinstance',
            name='fileTargetPath',
            field=models.CharField(max_length=255, null=True, verbose_name='\u6587\u4ef6\u4f20\u8f93\u7684\u76ee\u6807\u76ee\u5f55'),
        ),
    ]
