# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2017-09-19 23:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0004_nm_stepinstance_filetargetpath'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nm_stepinstance',
            name='scriptParam',
            field=models.CharField(default=False, max_length=255, null=True, verbose_name='\u6267\u884c\u811a\u672c\u7684\u53c2\u6570'),
        ),
    ]
