# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2017-09-26 11:40
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0008_auto_20170925_2234'),
    ]

    operations = [
        migrations.RenameField(
            model_name='nm_stepinstanceiplist',
            old_name='stepInstance_id',
            new_name='stepInstance',
        ),
        migrations.RenameField(
            model_name='nm_stepiplist',
            old_name='step_id',
            new_name='step',
        ),
    ]
