# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2017-10-11 23:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0009_auto_20170926_1140'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nm_step',
            name='name',
            field=models.CharField(max_length=255, null=True, verbose_name='\u8282\u70b9\u540d\u79f0'),
        ),
        migrations.AlterField(
            model_name='nm_stepiplist',
            name='step',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='job.Nm_Step', verbose_name='\u4f5c\u4e1a\u6b65\u9aa4id'),
        ),
    ]
