# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2017-10-15 19:46
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0012_auto_20171013_1452'),
    ]

    operations = [
        migrations.RenameField(
            model_name='nm_step',
            old_name='scriptId',
            new_name='script',
        ),
    ]
