# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2018-01-16 15:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0013_auto_20171015_1946'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nm_stepinstance',
            name='name',
            field=models.CharField(max_length=255, null=True, verbose_name='\u8282\u70b9\u540d\u79f0'),
        ),
    ]
